INSERT INTO SCAPEGOAT (text) VALUES ('my nephew');
INSERT INTO SCAPEGOAT (text) VALUES ('the ghost of Hitler');
INSERT INTO SCAPEGOAT (text) VALUES ('the Pope');
INSERT INTO SCAPEGOAT (text) VALUES ('my ex');
INSERT INTO SCAPEGOAT (text) VALUES ('a high school marching band');
INSERT INTO SCAPEGOAT (text) VALUES ('Dan Rather');
INSERT INTO SCAPEGOAT (text) VALUES ('a sad clown');
INSERT INTO SCAPEGOAT (text) VALUES ('the kid from Stranger Things');
INSERT INTO SCAPEGOAT (text) VALUES ('a professional cricket team');
INSERT INTO SCAPEGOAT (text) VALUES ('my Tinder date');
INSERT INTO SCAPEGOAT (text) VALUES ('your mom');
INSERT INTO SCAPEGOAT (text) VALUES ('Godzilla');
INSERT INTO SCAPEGOAT (text) VALUES ('a man with six fingers on his right hand');

INSERT INTO INTRO (text) VALUES ('Sorry I can''t come,');
INSERT INTO INTRO (text) VALUES ('Please forgive my absence,');
INSERT INTO INTRO (text) VALUES ('This is going to sound crazy but');
INSERT INTO INTRO (text) VALUES ('Get this:');
INSERT INTO INTRO (text) VALUES ('I can''t go because');
INSERT INTO INTRO (text) VALUES ('I know you''re going to hate me but');
INSERT INTO INTRO (text) VALUES ('I was only minding my own business and boom!');
INSERT INTO INTRO (text) VALUES ('I feel terrible but');
INSERT INTO INTRO (text) VALUES ('I regretfully cannot attend,');
INSERT INTO INTRO (text) VALUES ('The most unbelievable thing just happened,');
INSERT INTO INTRO (text) VALUES ('This is going to sound like an excuse but');
INSERT INTO INTRO (text) VALUES ('Holy shit! Get this!');
INSERT INTO INTRO (text) VALUES ('Holy Moses!');

INSERT INTO DELAY (text) VALUES ('gave me a hickey.');
INSERT INTO DELAY (text) VALUES ('tried to kill me.');
INSERT INTO DELAY (text) VALUES ('just shit the bed.');
INSERT INTO DELAY (text) VALUES ('won''t stop telling me knock knock jokes.');
INSERT INTO DELAY (text) VALUES ('gave me syphilis.');
INSERT INTO DELAY (text) VALUES ('poured lemonade in my gas tank.');
INSERT INTO DELAY (text) VALUES ('stabbed me.');
INSERT INTO DELAY (text) VALUES ('found my box of human teeth.');
INSERT INTO DELAY (text) VALUES ('posted my nudes on Instagram.');
INSERT INTO DELAY (text) VALUES ('stole my bicycle.');
INSERT INTO DELAY (text) VALUES ('beat me into submission.');
INSERT INTO DELAY (text) VALUES ('ate my homework.');
INSERT INTO DELAY (text) VALUES ('slept with my uncle.');
INSERT INTO DELAY (text) VALUES ('broke into my house.');
INSERT INTO DELAY (text) VALUES ('stole my keys.');
